// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsData.Modules.Matches.Infrastructure;

#nullable disable

namespace SportsData.Modules.Matches.Migrations
{
    [DbContext(typeof(MatchesDbContext))]
    [Migration("20251221152625_Phase1_Foundation")]
    partial class Phase1_Foundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("matches")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsData.Modules.Matches.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matches", "matches");
                });

            modelBuilder.Entity("SportsData.Modules.Matches.Domain.MatchStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CornersAway")
                        .HasColumnType("int");

                    b.Property<int>("CornersHome")
                        .HasColumnType("int");

                    b.Property<int>("FoulsAway")
                        .HasColumnType("int");

                    b.Property<int>("FoulsHome")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PossessionAway")
                        .HasColumnType("int");

                    b.Property<int>("PossessionHome")
                        .HasColumnType("int");

                    b.Property<int>("RedCardsAway")
                        .HasColumnType("int");

                    b.Property<int>("RedCardsHome")
                        .HasColumnType("int");

                    b.Property<int>("ShotsAway")
                        .HasColumnType("int");

                    b.Property<int>("ShotsHome")
                        .HasColumnType("int");

                    b.Property<int>("YellowCardsAway")
                        .HasColumnType("int");

                    b.Property<int>("YellowCardsHome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchStatistics", "matches");
                });
#pragma warning restore 612, 618
        }
    }
}
