// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsData.Modules.Matches.Infrastructure;

#nullable disable

namespace SportsData.Modules.Matches.Migrations
{
    [DbContext(typeof(MatchesDbContext))]
    partial class MatchesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SportsData.Modules.Matches.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("IX_Match_AwayTeamId");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("IX_Match_HomeTeamId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Match_Status");

                    b.HasIndex("SeasonId", "MatchDate")
                        .HasDatabaseName("IX_Match_SeasonId_MatchDate");

                    b.ToTable("matches_match", (string)null);
                });

            modelBuilder.Entity("SportsData.Modules.Matches.Domain.MatchStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CornersAway")
                        .HasColumnType("int");

                    b.Property<int>("CornersHome")
                        .HasColumnType("int");

                    b.Property<int>("FoulsAway")
                        .HasColumnType("int");

                    b.Property<int>("FoulsHome")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PossessionAway")
                        .HasColumnType("int");

                    b.Property<int>("PossessionHome")
                        .HasColumnType("int");

                    b.Property<int>("RedCardsAway")
                        .HasColumnType("int");

                    b.Property<int>("RedCardsHome")
                        .HasColumnType("int");

                    b.Property<int>("ShotsAway")
                        .HasColumnType("int");

                    b.Property<int>("ShotsHome")
                        .HasColumnType("int");

                    b.Property<int>("ShotsOnTargetAway")
                        .HasColumnType("int");

                    b.Property<int>("ShotsOnTargetHome")
                        .HasColumnType("int");

                    b.Property<int>("YellowCardsAway")
                        .HasColumnType("int");

                    b.Property<int>("YellowCardsHome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_MatchStatistics_MatchId");

                    b.ToTable("matches_matchStatistics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
