// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsData.Modules.ApiKeys.Infrastructure;

#nullable disable

namespace SportsData.Modules.ApiKeys.Migrations
{
    [DbContext(typeof(ApiKeysDbContext))]
    [Migration("20251227110012_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SportsData.Modules.ApiKeys.Domain.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitPerDay")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ApiKeys_IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiKeys_KeyHash");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_ApiKeys_OwnerId");

                    b.ToTable("apikeys_apikeys", (string)null);
                });

            modelBuilder.Entity("SportsData.Modules.ApiKeys.Domain.ApiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId")
                        .HasDatabaseName("IX_ApiUsageLogs_ApiKeyId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_ApiUsageLogs_Timestamp");

                    b.ToTable("apikeys_apiUsageLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
